- id: circleci-config-validate
  name: Validate CircleCI configs
  entry: scripts/circleci-config-validate.sh
  language: script
  verbose: false
  files: ^.circleci/.*yml$
  always_run: false
  args: []
