description: |
  Merge modules' configs, if there are changed files in the directory, into an additional config under .circleci/ in the
  checked-out source,
parameters:
  modules:
    description: Path to the file for the list of the modules to build
    type: string
    default: /tmp/modules-filtered.txt
  continue-config:
    description: Path to the internally-used config for continuation
    type: string
    default: .circleci/continue-config.yml
  cache:
    description: Cache the generated, reduced continuation config.
    type: boolean
    default: false
  cache-key:
    description: Override the default caching key, if caching is enabled.
    type: string
    default: continue-config-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
steps:
  - run:
      name: Merge configs
      command: |
        # If `modules` is unavailable, stop this job without continuation
        if [ ! -f "<< parameters.modules >>" ] || [ ! -s "<< parameters.modules >>" ]
        then
            echo 'Nothing to merge. Halting the job.'
            circleci-agent step halt
            exit 0
        fi
        # Convert a list of dirs to a list of config.yml
        sed -i -e 's/$/\/.circleci\/config.yml/g' "<< parameters.modules >>"

        xargs -a "<< parameters.modules >>" yq -y -s 'reduce .[] as $item ({}; . * $item)' | tee "<< parameters.continue-config >>"
  - when:
      condition: << parameters.cache >>
      steps:
        - save_cache:
            paths:
              - << parameters.continue-config >>
            key: << parameters.cache-key >>
